name: API Monitor on Dev

#on: workflow_dispatch
on: 
  push:
    branches:
      - 'main'
      - 'LSSP-241'
      - 'RC-001'
jobs:
  send-curl:
    env:
      PR_ID: pr-${{ github.event.number }}
      BUILD_TAG: latest
      APP_NAME: ls-licensing
      NAMESPACE: ls-dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Step is going to pass
      run: echo Passing step
      
    - name: Step is going to fail
      continue-on-error: true
      run: exit 1

    - name: Report Failure to Slack
      if: ${{ failure() }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{\"message\":\"RUSS it FAILED-- ${{ steps.send-curl.logs }} !  the BUILD_TAG-- ${{ env.BUILD_TAG }} !  the APP_NAME-- ${{ env.APP_NAME }} !  \", \"text\":\"RUSS Your text here\"}" ${{ secrets.SLACK_MONITOR_WEBHOOK_URL }}

    - name: Report Success to Slack
      if: ${{ success() }}
      run: >
        curl -X POST
        -H "Content-Type: application/json"
        -d "{\"message\":\"The monitor SUCCEEDED: ${{steps.e2e-test.logs.stdout}}  !  the env.API_URL: ${{ env.API_URL }} !  the ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} !  \", \"text\":\"RUSS Your text here\"}"
        ${{ secrets.SLACK_MONITOR_WEBHOOK_URL }}

    # steps:
    # - name: REST API with curl
    #   run: |
    #     curl -X POST -H "Content-Type: application/json" -d "{\"message\":\"RUSS here's the Logs-- ${{ steps.send-curl.logs }} !  the BUILD_TAG-- ${{ env.BUILD_TAG }} !  the APP_NAME-- ${{ env.APP_NAME }} !  \", \"text\":\"RUSS Your text here\"}" ${{ secrets.SLACK_MONITOR_WEBHOOK_URL }}

#        curl -X POST -H "Content-Type: application/json" -d "{\"message\":\"RUSS SOMETHING WAS PUSHED TO RC-001\", \"text\":\"RUSS Your text here\"}" ${{ secrets.SLACK_MONITOR_WEBHOOK_URL }}
    # Runs a single command using the runners shell
#    - name: Webhook
#      uses: distributhor/workflow-webhook
#      with:
#        url: ${{ secrets.SLACK_MONITOR_WEBHOOK_URL }}
#        json: '{ \"message\":\"RUSS Your message here\" }'

#jobs:
#  build:
#    name: Send a webhook maybe
#    runs-on: [self-hosted, linux, licensing, dev]
#    env:
#      PR_ID: pr-${{ github.event.number }}
#      BUILD_TAG: pr-${{ github.event.pull_request.head.sha }}
#      APP_NAME: ls-licensing
#    steps:
#    - name: Slack Notification
#      id: slack
#      uses: slackapi/slack-github-action@v1.23.0
#      with:
#        # For posting a rich message using Block Kit
#        payload: |
#          {
#            "text": "GitHub Action build result: ${{ job.status }}\nRUSS",
#            "blocks": [
#              {
#                "type": "section",
#                "text": {
#                  "type": "mrkdwn",
#                  "text": "GitHub Action build result: ${{ job.status }}\nRUSS"
#                }
#              }
#            ]
#          }
#      env:
#        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MONITOR_WEBHOOK_URL }}
#        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
