name: API Monitor on Dev

on: workflow_dispatch

jobs:
  test:
- name: Slack Notification
  id: slack
  uses: slackapi/slack-github-action@v1.23.0
  with:
    # For posting a rich message using Block Kit
    payload: |
      {
        "text": "Monitor Notification: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "RUSS: \n GitHub Action build result: ${{ job.status }}\n testUserId=${{ secrets.TESTUSERID }} \n testUserPwd=${{ secrets.TESTUSERPWD }} \n clientsUrl=${{ secrets.CLIENTS_URL }} \n baseUrl=https://${{ env.API_URL}}/${{ env.PR_ID }}${{ env.API_PREFIX }} "
            }
          }
        ]
      }
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MONITOR_WEBHOOK_URL }}
    SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
